version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_dbp_app
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=proyecto_dbp
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: proyecto_dbp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: proyecto_dbp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
